export const FETCH_SIGNIN_DATA_SUCCESS = "FETCH_SIGNIN_DATA_SUCCESS";
export const FETCH_SIGNUP_DATA_SUCCESS = "FETCH_SIGNUP_DATA_SUCCESS";
export const FETCH_SIGNIN_DATA_FAIL = "FETCH_SIGNIN_DATA_FAIL";

export const FETCH_PHOTOS_DATA_SUCCESS = "FETCH_PHOTOS_DATA_SUCCESS";
export const FETCH_PHOTOS_DATA_FAIL = "FETCH_PHOTOS_DATA_FAIL";