export const FETCH_SIGNIN_DATA_SUCCESS = "FETCH_SIGNIN_DATA_SUCCESS";
export const FETCH_SIGNUP_DATA_SUCCESS = "FETCH_SIGNUP_DATA_SUCCESS";
export const FETCH_SIGNIN_DATA_FAIL = "FETCH_SIGNIN_DATA_FAIL";
export const FETCH_SIGNOUT_DATA_SUCCESS = "FETCH_SIGNOUT_DATA_SUCCESS";

export const FETCH_USER_PHOTOS_DATA_SUCCESS = "FETCH_USER_PHOTOS_DATA_SUCCESS";
export const FETCH_USER_PHOTOS_DATA_FAIL = "FETCH_USER_PHOTOS_DATA_FAIL";

export const FETCH_USER_INFO_DATA_SUCCESS = "FETCH_USER_INFO_DATA_SUCCESS";
export const FETCH_USER_INFO_DATA_FAIL = "FETCH_USER_INFO_DATA_FAIL";

export const FETCH_PHOTOS_DATA_SUCCESS = "FETCH_PHOTOS_DATA_SUCCESS";
export const FETCH_PHOTOS_DATA_FAIL = "FETCH_PHOTOS_DATA_FAIL";
export const FETCH_NEW_PHOTO_DATA_SUCCESS = "FETCH_NEW_PHOTO_DATA_SUCCESS";
export const FETCH_PHOTO_USER_DATA_SUCCESS = "FETCH_PHOTO_USER_DATA_SUCCESS";
export const FETCH_PHOTO_USER_DATA_FAIL = "FETCH_PHOTO_USER_DATA_FAIL";

export const FETCH_COMMENTS_DATA_SUCCESS = "FETCH_COMMENTS_DATA_SUCCESS";
export const FETCH_COMMENTS_DATA_FAIL = "FETCH_COMMENTS_DATA_FAIL";

export const FETCH_NEW_COMMENT_DATA_SUCCESS = "FETCH_NEW_COMMENT_DATA_SUCCESS";
export const FETCH_NEW_COMMENT_DATA_FAIL = "FETCH_NEW_COMMENT_DATA_FAIL";

export const FETCH_LIKE_SUCCESS = "FETCH_LIKE_SUCCESS";
export const FETCH_LIKE_FAIL = "FETCH_LIKE_FAIL";